import type { Role } from './roles'

// Definisi semua permission yang ada di aplikasi
export const PERMISSIONS = {
  // Students
  STUDENT_VIEW_ALL: 'student:view:all',
  STUDENT_VIEW_OWN_CLASS: 'student:view:own_class',
  STUDENT_VIEW_SENSITIVE: 'student:view:sensitive',
  STUDENT_CREATE: 'student:create',
  STUDENT_UPDATE: 'student:update',
  STUDENT_ARCHIVE: 'student:archive',
  STUDENT_IMPORT: 'student:import',
  STUDENT_EXPORT: 'student:export',
  STUDENT_EXPORT_OWN: 'student:export:own',
  STUDENT_VERIFY: 'student:verify',

  // Teachers
  TEACHER_VIEW: 'teacher:view',
  TEACHER_MANAGE: 'teacher:manage',

  // Classrooms
  CLASSROOM_VIEW_ALL: 'classroom:view:all',
  CLASSROOM_VIEW_OWN: 'classroom:view:own',
  CLASSROOM_MANAGE: 'classroom:manage',

  // School Years
  SCHOOL_YEAR_VIEW: 'school_year:view',
  SCHOOL_YEAR_MANAGE: 'school_year:manage',

  // Reports
  REPORT_VIEW_ALL: 'report:view:all',
  REPORT_EXPORT: 'report:export',
  SUBJECT_VIEW: 'subject:view',
  SUBJECT_MANAGE: 'subject:manage',
  SCORE_VIEW_ALL: 'score:view:all',
  SCORE_VIEW_OWN_CLASS: 'score:view:own_class',
  SCORE_MANAGE_ALL: 'score:manage:all',
  SCORE_MANAGE_OWN_CLASS: 'score:manage:own_class',
  REPORT_INTELLIGENCE: 'report:intelligence',

  // Users
  USER_VIEW: 'user:view',
  USER_MANAGE: 'user:manage',

  // Settings
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage',

  // Audit
  AUDIT_VIEW: 'audit:view',

} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]

/**
 * Matrix hak akses per role — harus sinkron dengan ROLE_PERMISSIONS di gas-backend/Main.gs.
 * Principal dapat melihat Settings secara read-only.
 */
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  admin: [
    PERMISSIONS.STUDENT_VIEW_ALL,
    PERMISSIONS.STUDENT_VIEW_SENSITIVE,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_ARCHIVE,
    PERMISSIONS.STUDENT_IMPORT,
    PERMISSIONS.STUDENT_EXPORT,
    PERMISSIONS.STUDENT_VERIFY,
    PERMISSIONS.TEACHER_VIEW,
    PERMISSIONS.TEACHER_MANAGE,
    PERMISSIONS.CLASSROOM_VIEW_ALL,
    PERMISSIONS.CLASSROOM_MANAGE,
    PERMISSIONS.SCHOOL_YEAR_VIEW,
    PERMISSIONS.SCHOOL_YEAR_MANAGE,
    PERMISSIONS.REPORT_VIEW_ALL,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_INTELLIGENCE,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.SUBJECT_MANAGE,
    PERMISSIONS.SCORE_VIEW_ALL,
    PERMISSIONS.SCORE_MANAGE_ALL,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
  ],
  principal: [
    PERMISSIONS.STUDENT_VIEW_ALL,
    PERMISSIONS.STUDENT_VIEW_SENSITIVE,
    PERMISSIONS.STUDENT_EXPORT,
    PERMISSIONS.STUDENT_VERIFY,
    PERMISSIONS.TEACHER_VIEW,
    PERMISSIONS.CLASSROOM_VIEW_ALL,
    PERMISSIONS.SCHOOL_YEAR_VIEW,
    PERMISSIONS.REPORT_VIEW_ALL,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_INTELLIGENCE,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.SUBJECT_MANAGE,
    PERMISSIONS.SCORE_VIEW_ALL,
    PERMISSIONS.SCORE_MANAGE_ALL,
    PERMISSIONS.SETTINGS_VIEW,
  ],
  teacher: [
    PERMISSIONS.STUDENT_VIEW_OWN_CLASS,
    PERMISSIONS.STUDENT_EXPORT_OWN,
    PERMISSIONS.CLASSROOM_VIEW_OWN,
    PERMISSIONS.SCHOOL_YEAR_VIEW,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.SCORE_VIEW_OWN_CLASS,
    PERMISSIONS.SCORE_MANAGE_OWN_CLASS,
  ],
}
